// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GameMap: typeof import('./src/components/GameMap.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PlayGround: typeof import('./src/components/PlayGround.vue')['default']
    ScoreBoard: typeof import('./src/components/ScoreBoard.vue')['default']
  }
}
